{% set name = "shredder" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/shredder/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1364c1a7838408c466a396acb037dd901264e4ba6c04d2302fc1069da3ca5086

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - numba
    - ngmix >=2
    - esutil
    - galsim

test:
  imports:
    - shredder

about:
  home: https://github.com/esheldon/shredder
  summary: An astronomical image deblender
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
